version: '3.8'

services:
  db:
    image: nealma22/sqlpinacoteca:v1
    container_name: mysql_pinacoteca
    restart: always

  web:
    image: nealma22/phppinacoteca:v1
    container_name: web_pinacoteca
    ports:
      - "80:80"
    depends_on:
      - db
